title: coffeetableviz
description: Simple charts. Clear stories. Data, design and the interesting bit in between.
url: "https://adamgreen1708.github.io"
baseurl: "/chart-templates"
author:
  name: Adam Green
  url: "https://coffeetableviz.wordpress.com"
lang: en-GB
timezone: Europe/London
permalink: /stories/:slug/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

