title: coffeetableviz
description: Simple charts. Clear stories. Data, design and the interesting bit in between.
url: "https://coffeetableviz.com"
baseurl: ""
author:
  name: Adam Green
  url: "https://coffeetableviz.com"
lang: en-GB
timezone: Europe/London
permalink: /stories/:slug/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
collections:
  blockbuster_quotes:
    output: true
    permalink: /series/blockbuster-quote/:name/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: blockbuster_quotes
    values:
      layout: blockbuster_quote

