CHART_CONFIG = {
    "data_file": "data/your_file.csv",
    "data_format": "wide",
    "chart_type": "bar",

    "x_col": "category_or_x",
    "y_col": "value_or_y",
    "series_col": None,
    "value_col": None,

    "title": "Your headline title",
    "subtitle": "Your explanatory subtitle",
    "source_text": "Source: ...",
    "footer_left": "Adam Green | coffeetableviz",

    "story_angle": "category_comparison",
    "focus_series": None,
    "secondary_series": None,
    "label_strategy": "focus_only",

    "x_is_datetime": False,
    "x_tick_rotation": 0,
    "y_axis_min": 0,
    "y_axis_max": None,
    "y_tick_interval": 25,
    "y_tick_format": ".0f",

    "line_width": 2.6,
    "marker_size": 0,
    "show_markers": False,
    "auto_end_labels": True,
    "sort_descending": False,

    "reference_lines": [],
    "highlight_points": [],
    "annotate_points": [],
    "end_labels": [],

    "context_style": {
        "color": "#D9D9D9",
        "linewidth": 0.8,
        "alpha": 0.25,
    },
    "focus_style": {
        "color": "#1F8FA8",
        "linewidth": 3.2,
        "alpha": 1.0,
    },
    "secondary_style": {
        "color": "#7A7A7A",
        "linewidth": 2.0,
        "alpha": 0.9,
    },

    "fig_width": 8.5,
    "fig_height": 8.5,
    "title_fontsize": 24,
    "subtitle_fontsize": 14,
    "tick_label_fontsize": 13,
    "footer_fontsize": 10,
    "title_wrap_width": 34,
    "subtitle_wrap_width": 72,
    "title_x": 0.14,
    "title_y": 0.955,
    "subtitle_x": 0.14,
    "subtitle_y": 0.89,
    "footer_left_x": 0.14,
    "footer_right_x": 0.96,
    "footer_y": 0.06,
    "plot_top": 0.74,
    "plot_bottom": 0.16,
    "plot_left": 0.14,
    "plot_right": 0.96,
}
